add daily info
Three-and-a-half-stumps/firecamp_bot pull request #17
Opened 2023-07-04 20:18 UTC by lega4e

2023-07-04 20:28 UTC, lega4e commented on src/domain/config.py
pin message

2023-07-04 20:28 UTC, lega4e commented on src/managers/sheet/sheet.py
> +  def getCurrentMonthEdges(self) -> (dt.datetime, dt.datetime):
remove getMonthEnd

2023-07-04 20:28 UTC, lega4e commented on src/utils/tg/send_message.py
> +      #   _logger.message(pieces, kwargs['chat_id'])
!!!

2023-07-05 11:33 UTC, KennySuke requested changes
В тикете написано, что надо выводить процент для собранной суммы, у тебя в InfoManager/dailySummary только сумма. Думаю, надо вообще вынести проценты из handleTotal в мастер

2023-07-05 22:05 UTC, KennySuke requested changes

2023-07-05 22:05 UTC, KennySuke commented on src/managers/info.py
> +  def currentMonthEdges(self) -> (dt.datetime, dt.datetime):
Зачем дублирование sheet.getCurrentMonthEdges, если ниже ты эту так и не используешь

2023-07-06 14:12 UTC, lega4e commented on src/managers/info.py
> +  def percent(total: int, rent: int) -> str:
кстати да)

2023-07-06 14:17 UTC, lega4e commented on src/managers/info.py
> +    title = P('📈 ') + P(
можно, вынес

2023-07-06 14:18 UTC, lega4e commented on src/managers/info.py
> +  def currentMonthEdges(self) -> (dt.datetime, dt.datetime):
Подразумевается, что остальные классы не должны непосредственно использовать sheet для получения какой-либо информации, это привилегия InfoManager'а. Таким образом, если кому-то нужно будет узнать границы месяца, они должны обращаться к InfoManager, а не к Sheet

2023-07-06 14:23 UTC, KennySuke approved these changes

2023-07-06 15:34 UTC, merged