Изменение /total. Добавил отсчёт дней до конца месяца.
Three-and-a-half-stumps/firecamp_bot pull request #6
Opened 2023-06-28 17:32 UTC by ComradeCucumber

2023-06-28 17:40 UTC, lega4e requested changes

2023-06-28 17:40 UTC, lega4e commented on src/managers/tg/user.py
> +      timedif = dt.datetime(int(monthtime[2]), int(monthtime[1]) + 1, 1) - dt.datetime.today()
Начало месяца находится в гугл табличке (да, месяц может не начинаться с первого числа, мы отсчитываем арендный месяц). Так что начало нужно брать из гугл-таблички

2023-06-28 17:40 UTC, lega4e commented on src/managers/tg/user.py
> +    def gettimedif() -> f-string:
Не надо пж без необходимости объявлять функции внутри функций. Здесь достаточно было в коде основной функции посчитать дифф, сохранить в переменную и использовать

2023-06-28 17:40 UTC, lega4e commented on src/managers/tg/user.py
> +      timedif = dt.datetime(int(monthtime[2]), int(monthtime[1]) + 1, 1) - dt.datetime.today()
Часы излишни

2023-06-28 17:40 UTC, lega4e commented on src/managers/tg/user.py
> + До конца месяца осталось {gettimedif()}")
Я бы ещё добавил "арендного месяца", чтобы никто не путался

2023-06-30 13:30 UTC, ComradeCucumber commented
Все комментарии учтены и исправлены.
Актуальная проблема: довольно громоздкий код с добавлением окончания арендного месяца относительно последней даты в таблице. Пытался безуспешно найти способ добавить один месяц через библиотеку, если кто знает как - буду блогадарен.

2023-06-30 18:30 UTC, lega4e requested changes

2023-06-30 18:30 UTC, lega4e commented on src/managers/master.py
> +    return self.sheet.getmonthEnd()
Давай придерживаться camelCase'а (Month с БОЛЬШОЙ буквы!!)

2023-06-30 18:30 UTC, lega4e commented on src/managers/sheet/sheet.py
> +    import datetime as dt
Импортируй не локально, а в начале файла

2023-06-30 18:30 UTC, lega4e commented on src/managers/tg/user.py
> + До конца арендного месяца осталось {timeDifference.days}д.")
Разбивай строку на две, когда она слишком длинная и прибавляй + (а вообще плюс можно не писать, они. итак сложатся)

2023-06-30 20:34 UTC, lega4e approved these changes

2023-06-30 20:34 UTC, merged