Added things_count and things_count_by_rail
Three-and-a-half-stumps/firecamp_bot pull request #7
Opened 2023-06-28 22:04 UTC by KennySuke

2023-06-29 09:18 UTC, lega4e requested changes

2023-06-30 18:37 UTC, lega4e requested changes

2023-06-30 18:37 UTC, lega4e commented on src/managers/tg/user.py
> +    self.send(f"Вещей - {self.master.getCountAllThings()} шт.")
По умолчанию нужно пользоваться одинарными кавычками 'ddd'

2023-06-30 18:37 UTC, lega4e commented on src/managers/tg/user.py
> +      if countOnRail:
Давай будем явно сравнивать числа `countOnRail > 0` или `countOnRail != 0` — это улучшает читаемость. Так ифать можно лишь булевые значения

2023-06-30 19:07 UTC, KennySuke commented on src/managers/tg/user.py
> +      if countOnRail:
Хейтер JS стиля...

2023-06-30 20:25 UTC, lega4e approved these changes

2023-06-30 20:28 UTC, merged